name: Add Claude Review Button

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-review-button:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Add Claude Review Button
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            
            // Check if review button comment already exists
            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: pull_number,
            });
            
            const hasReviewButton = comments.data.some(comment => 
              comment.body.includes('🤖 Claude Code Review') && 
              comment.user.login === 'github-actions[bot]'
            );
            
            if (!hasReviewButton) {
              // Create the review button comment
              const reviewBody = [
                "## 🤖 Claude Code Review",
                "",
                "Ready for a code review? Use one of these methods:",
                "",
                "### 🚀 Quick Commands (Recommended)",
                "Comment on this PR with any of these commands:",
                "- `/claude-review` or `/review-comprehensive` - Full comprehensive review",
                "- `/review-security` - Security-focused review",
                "- `/review-performance` - Performance analysis",
                "- `/review-testing` - Test coverage and quality",
                "- `/review-godot` - Godot 4.3 best practices",
                "",
                "### 📋 Manual Trigger",
                "Alternatively, you can manually trigger the review:",
                `1. Go to the [Actions tab](https://github.com/${owner}/${repo}/actions/workflows/claude-code-review.yml)`,
                "2. Click \"Run workflow\"",
                `3. Enter PR number: **${pull_number}**`,
                "4. Select review focus",
                "5. Click \"Run workflow\"",
                "",
                "*The review will be posted as a comment on this PR when complete.*",
                "",
                "---",
                "*💡 Tip: Use specific review focuses for targeted feedback on particular aspects of your code.*"
              ].join("\n");
              
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: pull_number,
                body: reviewBody
              });
            }