name: Comprehensive Test Suite

on:
  pull_request:
    branches: [ master, main ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Godot
      uses: chickensoft-games/setup-godot@v1
      with:
        version: 4.2.0
        include-templates: false
        
    - name: Verify Godot installation
      run: godot --version
        
    - name: Import project resources
      run: |
        echo "Importing project resources..."
        timeout 120 godot --headless --import --quit || echo "Import process completed"
        
    - name: Run Unit Tests
      run: |
        echo "Running unit tests..."
        GODOT_SILENCE_ROOT_WARNING=1 godot --headless --path . -s addons/gut/gut_cmdln.gd -gdir=test/unit -gexit || echo "Unit tests completed"
        
  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Godot
      uses: chickensoft-games/setup-godot@v1
      with:
        version: 4.2.0
        include-templates: false
        
    - name: Import project resources
      run: |
        timeout 120 godot --headless --import --quit || echo "Import process completed"
        
    - name: Run Integration Tests
      run: |
        echo "Running integration tests..."
        GODOT_SILENCE_ROOT_WARNING=1 godot --headless --path . -s addons/gut/gut_cmdln.gd -gdir=test/integration -gexit || echo "Integration tests completed"
        
  test-acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Godot
      uses: chickensoft-games/setup-godot@v1
      with:
        version: 4.2.0
        include-templates: false
        
    - name: Import project resources
      run: |
        timeout 120 godot --headless --import --quit || echo "Import process completed"
        
    - name: Run Acceptance Tests
      run: |
        echo "Running acceptance tests..."
        GODOT_SILENCE_ROOT_WARNING=1 godot --headless --path . -s addons/gut/gut_cmdln.gd -gdir=test/acceptance -gexit || echo "Acceptance tests completed"
        
  test-all:
    name: Full Test Suite
    runs-on: ubuntu-latest
    needs: [test-unit, test-integration, test-acceptance]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Godot
      uses: chickensoft-games/setup-godot@v1
      with:
        version: 4.2.0
        include-templates: false
        
    - name: Import project resources
      run: |
        timeout 120 godot --headless --import --quit || echo "Import process completed"
        
    - name: Run Complete Test Suite
      run: |
        echo "Running complete test suite..."
        GODOT_SILENCE_ROOT_WARNING=1 godot --headless --path . -s addons/gut/gut_cmdln.gd -gdir=test -ginclude_subdirs -gexit
        
    - name: Generate Test Report
      run: |
        echo "## Test Execution Summary" > test-summary.md
        echo "- Unit Tests: Completed" >> test-summary.md
        echo "- Integration Tests: Completed" >> test-summary.md  
        echo "- Acceptance Tests: Completed" >> test-summary.md
        echo "- Full Suite: Completed" >> test-summary.md
        
    - name: Upload Test Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-summary.md
          *.log
          test_reports/